// <auto-generated />
namespace IT_Project_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changedDocumentModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedDocumentModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201803242129363_changedDocumentModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
